#!/usr/bin/env node

/**
 * Validation script for patches.json configuration
 * Used by CI workflow
 */

import { readFileSync, existsSync } from 'node:fs';

try {
  const config = JSON.parse(readFileSync('patches.json', 'utf-8'));
  
  if (!config.path || !config.includePatterns) {
    throw new Error('Invalid patches.json: missing required fields (path, includePatterns)');
  }
  
  // Check that patches directory exists (optional - auto-generated by workflow)
  if (config.path && !existsSync(config.path)) {
    console.log('Note: Patches directory does not exist yet - will be generated by auto-patch job');
  } else if (config.path && existsSync(config.path)) {
    console.log('  Patches directory:', config.path);
  }
  
  console.log('patches.json is valid');
  console.log('  Path:', config.path || '(auto-generated)');
  console.log('  Include patterns:', config.includePatterns.join(', '));
  
  process.exit(0);
} catch (e) {
  console.error('Validation failed:', e.message);
  process.exit(1);
}
